# Generated by Django 5.1.6 on 2025-02-13 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('participants', models.IntegerField(blank=True)),
                ('fund_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fund_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fund_per_person', models.DecimalField(decimal_places=2, max_digits=6)),
                ('batches', models.CharField(help_text='Comma-separated list of batches (e.g., 2020, 2021, 2022)', max_length=200)),
                ('coordinator1_phone', models.CharField(blank=True, max_length=20)),
                ('coordinator2_phone', models.CharField(blank=True, max_length=20)),
                ('branches', models.ManyToManyField(blank=True, help_text='Branches invited to the event', related_name='events', to='fundmanager.branch')),
                ('coordinator1', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='events_managing1', to=settings.AUTH_USER_MODEL)),
                ('coordinator2', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='events_managing2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fundmanager.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(blank=True, max_length=20)),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='fundmanager.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
